permalink: /:categories/:year/:month/:title/

url: http://suvashthapaliya.com

author: Bikram Adhikari 
description: Bikram Adhikari's online tinkerhouse

title: Bikram Adhikari
subtitle: ~ Think Different ~
